/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urnaeletronica;

import java.io.IOException;
import java.util.Arrays;
import java.util.Collections;

/**
 *
 * @author DELL
 */
public class Urna extends javax.swing.JFrame {

    public static int inicio = 0;
    public static Candidato c = new Candidato();

    /**
     * Creates new form JInicio
     */
    public Urna() {
        menuOpcoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEleicao = new javax.swing.JButton();
        btnPlanilha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnCadastro.setLabel("Cadastro");
        btnCadastro.setName(""); // NOI18N
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Software de Eleição");

        btnEleicao.setText("Eleição");
        btnEleicao.setName(""); // NOI18N
        btnEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleicaoActionPerformed(evt);
            }
        });

        btnPlanilha.setText("Planilha");
        btnPlanilha.setToolTipText("");
        btnPlanilha.setName(""); // NOI18N
        btnPlanilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanilhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPlanilha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlanilha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        Cadastro c = new Cadastro();
        c.carregaTela();
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnPlanilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanilhaActionPerformed
       resultadoEleicao();
    }//GEN-LAST:event_btnPlanilhaActionPerformed

    private void btnEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleicaoActionPerformed
        iniciarEleicao();
    }//GEN-LAST:event_btnEleicaoActionPerformed

    public void menuOpcoes() {
        if (inicio == 0) {
            initComponents();
            ++inicio;
        }
    }

    public void iniciarEleicao() {
        Eleicao e = new Eleicao();
        e.carregaTela();
    }

    public void cadastroCandidatos(String numero, String nome, String partido, String cargo, String dir) {
        c.verifica(numero);
        if (c.jaExiste == false) {
            for (int i = 0; i < c.candidatos.length; i++) {
                if (c.candidatos[i][0] == null) {
                    c.candidatos[i][0] = numero;
                    c.candidatos[i][1] = nome;
                    c.candidatos[i][2] = partido;
                    c.candidatos[i][3] = cargo;
                    c.candidatos[i][4] = "0";
                    c.candidatos[i][5] = dir;
                    break;
                }
            }
        }
    }

    public void resultadoEleicao() {
        
        Planilha p = new Planilha();
        p.carregaTela();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEleicao;
    private javax.swing.JButton btnPlanilha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
